"""
Message Processing Schemas for CareFlow AI.

Source of truth: docs/api.md - Section 19 and docs/ai-agent-specification.md.
"""

import uuid
from typing import Optional
from pydantic import BaseModel, Field

from app.models.enums import CommunicationChannel, AIIntentCategory
from app.schemas.common import DataResponse


class MessageProcessRequest(BaseModel):
    """
    Client message payload submitted for AI agent processing.
    """
    client_id: uuid.UUID = Field(
        ...,
        description="UUID of the client sending the message.",
    )
    message: str = Field(
        ...,
        min_length=1,
        max_length=2000,
        description="Text content of the incoming client message.",
    )
    channel: CommunicationChannel = Field(
        default=CommunicationChannel.WEB,
        description="Channel through which the message was received.",
    )


class MessageProcessResponseData(BaseModel):
    """
    Processed output details generated by the AI agent and backend services.
    """
    interaction_id: uuid.UUID = Field(
        ...,
        description="UUID of the recorded incoming interaction.",
    )
    intent: AIIntentCategory = Field(
        ...,
        description="Classified intent category.",
    )
    response: str = Field(
        ...,
        description="Safe, non-clinical supportive response text for the client.",
    )
    escalated: bool = Field(
        default=False,
        description="True if the interaction was escalated for human review.",
    )
    escalation_id: Optional[uuid.UUID] = Field(
        default=None,
        description="UUID of the created escalation record if escalated.",
    )
    followup_id: Optional[uuid.UUID] = Field(
        default=None,
        description="UUID of the created follow-up task if action is required.",
    )
    barrier_detected: Optional[str] = Field(
        default=None,
        description="Identified barrier type if a barrier to care was reported.",
    )


class MessageProcessResponse(DataResponse[MessageProcessResponseData]):
    """Standard envelope for message processing response."""
    pass
